package com.exe201.pillow.domain;

import static com.exe201.pillow.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DefaultSizeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDefaultSizeAllPropertiesEquals(DefaultSize expected, DefaultSize actual) {
        assertDefaultSizeAutoGeneratedPropertiesEquals(expected, actual);
        assertDefaultSizeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDefaultSizeAllUpdatablePropertiesEquals(DefaultSize expected, DefaultSize actual) {
        assertDefaultSizeUpdatableFieldsEquals(expected, actual);
        assertDefaultSizeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDefaultSizeAutoGeneratedPropertiesEquals(DefaultSize expected, DefaultSize actual) {
        assertThat(actual)
            .as("Verify DefaultSize auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDefaultSizeUpdatableFieldsEquals(DefaultSize expected, DefaultSize actual) {
        assertThat(actual)
            .as("Verify DefaultSize relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getLength()).as("check length").isEqualTo(expected.getLength()))
            .satisfies(a -> assertThat(a.getWidth()).as("check width").isEqualTo(expected.getWidth()))
            .satisfies(a ->
                assertThat(a.getExtraPrice())
                    .as("check extraPrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getExtraPrice())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDefaultSizeUpdatableRelationshipsEquals(DefaultSize expected, DefaultSize actual) {
        assertThat(actual)
            .as("Verify DefaultSize relationships")
            .satisfies(a -> assertThat(a.getPillow()).as("check pillow").isEqualTo(expected.getPillow()));
    }
}
