package com.exe201.pillow.domain;

import static com.exe201.pillow.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PillowAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPillowAllPropertiesEquals(Pillow expected, Pillow actual) {
        assertPillowAutoGeneratedPropertiesEquals(expected, actual);
        assertPillowAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPillowAllUpdatablePropertiesEquals(Pillow expected, Pillow actual) {
        assertPillowUpdatableFieldsEquals(expected, actual);
        assertPillowUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPillowAutoGeneratedPropertiesEquals(Pillow expected, Pillow actual) {
        assertThat(actual)
            .as("Verify Pillow auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPillowUpdatableFieldsEquals(Pillow expected, Pillow actual) {
        assertThat(actual)
            .as("Verify Pillow relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getMaterial()).as("check material").isEqualTo(expected.getMaterial()))
            .satisfies(a ->
                assertThat(a.getBasePrice()).as("check basePrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getBasePrice())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPillowUpdatableRelationshipsEquals(Pillow expected, Pillow actual) {
        // empty method
    }
}
